In [1]:
import numpy as np
import scipy.signal

In [2]:
# Method for convolutions in 1-dimension
def conv1D(X, W, p=0, s=1):

    W_rotated = np.array(W[::-1])    # Rotate the kernel horizontally
    X_padded = np.array(X)
    
    # Pad the signal with 0's on both ends
    if p > 0:
        zero_pad = np.zeros(shape=p)
        X_padded = np.concatenate([zero_pad, X_padded, zero_pad])

    result = []                      # Stores the result of the convolution

    # Shift the kernel over the signal by the stride
    for i in range(0, int(len(X) / s), s):
        result.append(np.sum(X_padded[i:i + W_rotated.shape[0]] * W_rotated))

    return np.array(result)

In [7]:
# Create a test signal and kernel and test the method against NumPy
X = [1, 3, 2, 4, 5, 6, 1, 3]
W = [1, 0, 3, 1, 2]

print("Convolution (1D) Implementation:", conv1D(X, W, p=2, s=1))
print("NumPy Results:", np.convolve(X, W, mode="same"))

Convolution (1D) Implementation: [ 5. 14. 16. 26. 24. 34. 19. 22.]
NumPy Results: [ 5 14 16 26 24 34 19 22]


In [9]:
# Method for convolution in 2-dimensions
def conv2D(X, W, p=(0, 0), s=(1, 1)):

    W_rotated = np.array(W)[::-1, ::-1]    # Rotate the kernel horizontally and vertically
    X_original = np.array(X)

    # Get the dimensions for the padded signal
    n1 = X_original.shape[0] + (2 * p[0])
    n2 = X_original.shape[1] + (2 * p[1])

    # Pad the signal with 0's on all sides
    X_padded = np.zeros(shape=(n1, n2))
    X_padded[p[0]:p[0] + X_original.shape[0], p[1]:p[1] + X_original.shape[1]] = X_original

    result = []                            # Stores the result of the convolution

    # Shift the kernel over the signal horizontally by the stride
    for i in range(0, int((X_padded.shape[0] - W_rotated.shape[0]) / s[0]) + 1, s[0]):
        result.append([])

        # Shift the kernel over the signal vertically by the stride
        for j in range(0, int((X_padded.shape[1] - W_rotated.shape[1]) / s[1]) + 1, s[1]):
            X_sub = X_padded[i:i + W_rotated.shape[0], j:j + W_rotated.shape[1]]
            result[-1].append(np.sum(X_sub * W_rotated))

    return np.array(result)

In [12]:
# Create a test signal and kernel and test the method against SciPy
X = [[1, 3, 2, 4], [5, 6, 1, 3], [1, 2, 0, 2], [3, 4, 3, 2]]
W = [[1, 0, 3], [1, 2, 1], [0, 1, 1]]

print("Convolution (1D) Implementation:\n", conv2D(X, W, p=(1, 1), s=(1, 1)))
print("\nSciPy Results:\n", scipy.signal.convolve2d(X, W, mode="same"))

Convolution (1D) Implementation:
 [[11. 25. 32. 13.]
 [19. 25. 24. 13.]
 [13. 28. 25. 17.]
 [11. 17. 14.  9.]]

SciPy Results:
 [[11 25 32 13]
 [19 25 24 13]
 [13 28 25 17]
 [11 17 14  9]]
